const equipment = [
  {family:'GRS · Type B',name:'B1N',category:'reles',evidence:'contextual',desc:'Relé neutro de corrente contínua. A designação completa, resistência de bobina e contatos definem a aplicação.',detail:'Inventário: 56001-734 GR1 e variantes'},
  {family:'GRS · Type B',name:'B1PO',category:'reles',evidence:'pending',desc:'Relé polarizado listado com bobinas 100/100 Ω. A função exata deve ser vinculada ao boletim do modelo.',detail:'Inventário: B1PO 100/100 Ω'},
  {family:'GRS · Type B',name:'B2V',category:'reles',evidence:'confirmed',desc:'Família de relés de via do tipo vane. Catálogos públicos confirmam variantes de CA e diferentes arranjos de contatos.',detail:'Inventário: 56005-100 GR12'},
  {family:'GRS · Temporização',name:'B2TE',category:'reles',evidence:'contextual',desc:'Relé temporizado empregado quando a lógica exige retardo controlado. O inventário contém faixas em segundos e minutos.',detail:'Faixas: 4–64 s e 1–8 min'},
  {family:'GRS · Código',name:'B2CT',category:'reles',evidence:'pending',desc:'Família associada a taxas de código. As variantes de 75 e 180 exigem o manual específico para descrição detalhada.',detail:'Inventário: 75 e 180 rate'},
  {family:'GRS · Temporização',name:'A62-451',category:'reles',evidence:'contextual',desc:'Conjunto de relé térmico temporizado Type B2 identificado no inventário.',detail:'57263-855 GR2'},
  {family:'US&S · Plug-in',name:'PN-150B',category:'reles',evidence:'contextual',desc:'Relé vital plug-in polarizado/bias, encontrado em diferentes resistências e arranjos de contatos.',detail:'Inventário: UN322500-901 e 400 Ω'},
  {family:'US&S · Plug-in',name:'PN-150N',category:'reles',evidence:'contextual',desc:'Relé neutro plug-in. A resistência da bobina e a configuração F/B distinguem as variantes.',detail:'Inventário: 100 Ω e 240 Ω'},
  {family:'US&S · Plug-in',name:'PN-258BSR / PN-259BSR',category:'reles',evidence:'pending',desc:'Relés bias de interface/supervisão listados com 350 Ω e configurações específicas de contatos.',detail:'Identificação funcional pendente de manual'},
  {family:'Circuito de via',name:'Transformador 54940',category:'via',evidence:'pending',desc:'Transformador associado ao circuito de via, listado como GR.9 / 13AU-265 em diferentes armários.',detail:'Confirmar relações e ligação pelo desenho'},
  {family:'Circuito de via',name:'Reator ajustável 53722-2',category:'via',evidence:'pending',desc:'Elemento de ajuste do comportamento elétrico do circuito. Seu valor e posição dependem do esquema correspondente.',detail:'Inventário: GR.9'},
  {family:'Circuito de via',name:'Balancing impedance',category:'via',evidence:'contextual',desc:'Elemento usado para compatibilizar caminhos de retorno e sinais do circuito de via, conforme a arquitetura instalada.',detail:'Aplicação depende do tipo de circuito'},
  {family:'Circuito de via',name:'Resistores de ajuste',category:'via',evidence:'contextual',desc:'Limitam ou ajustam corrente e níveis de operação. Valores e derivações devem ser preservados conforme o projeto.',detail:'Fixos, variáveis e multi-seção'},
  {family:'Conversão de energia',name:'Retificadores BQA / BK116',category:'energia',evidence:'pending',desc:'Convertem alimentação alternada em contínua para circuitos e relés. Há diversas referências de fabricação no inventário.',detail:'59847-4 GR1 e variantes'},
  {family:'Alimentação',name:'Banco de baterias Ni-Cd',category:'energia',evidence:'contextual',desc:'Reserva de energia para manter funções essenciais diante de perda da alimentação principal.',detail:'Capacidade e tensão a confirmar em campo'},
  {family:'Proteção elétrica',name:'Centelhadores',category:'energia',evidence:'contextual',desc:'Dispositivos de proteção contra surtos, identificados por tensões nominais distintas.',detail:'32 Vcc/25 Vca e 250 Vcc/175 Vca'},
  {family:'Proteção elétrica',name:'Supressores',category:'energia',evidence:'contextual',desc:'Atenuam transitórios produzidos por cargas indutivas e comutação, protegendo contatos e circuitos.',detail:'Inventário: 1 mfd / 12 Ω e variantes'},
  {family:'Interface eletromecânica',name:'Bases GRS B1 / B2',category:'interface',evidence:'contextual',desc:'Soquetes que conectam bobinas e contatos do relé à fiação fixa e asseguram a montagem correspondente.',detail:'Base não é o relé'},
  {family:'Interface eletromecânica',name:'Bases US&S',category:'interface',evidence:'contextual',desc:'Bases simples e duplas para famílias plug-in US&S, com contatos e arranjos próprios.',detail:'Compatibilidade deve ser verificada por modelo'},
  {family:'Terminação',name:'K3 / K40',category:'interface',evidence:'pending',desc:'Terminais e barras de conexão usados para organizar a distribuição interna dos circuitos.',detail:'K40 listado como barra de 12 terminais'},
  {family:'Telecomunicações',name:'Bloco BL-I',category:'interface',evidence:'pending',desc:'Bloco de terminação de telecomunicações presente no inventário das caixas.',detail:'Função detalhada depende do plano de cabos'},
  {family:'Abrigo de campo',name:'Armário simples / duplo',category:'interface',evidence:'contextual',desc:'Invólucro que reúne equipamentos, proteção, terminação e interface com cabos de campo.',detail:'Associado a base civil e entrada de dutos'}
];
const labels={confirmed:'Confirmado',contextual:'Contextual',pending:'A verificar'};
const grid=document.querySelector('#equipment-grid'); const empty=document.querySelector('.empty');
let current='todos';
function render(){const term=document.querySelector('#search').value.toLocaleLowerCase('pt-BR');const shown=equipment.filter(x=>(current==='todos'||x.category===current)&&(`${x.family} ${x.name} ${x.desc} ${x.detail}`.toLocaleLowerCase('pt-BR').includes(term)));grid.innerHTML=shown.map(x=>`<article class="equipment-card"><div class="card-top"><span class="family">${x.family}</span><span class="evidence ${x.evidence}">${labels[x.evidence]}</span></div><h3>${x.name}</h3><p>${x.desc}</p><footer>${x.detail}</footer></article>`).join('');empty.hidden=shown.length>0}
document.querySelector('#search').addEventListener('input',render);document.querySelectorAll('.filters button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filters .selected').classList.remove('selected');b.classList.add('selected');current=b.dataset.filter;render()}));
const menu=document.querySelector('.menu-button');const nav=document.querySelector('.topbar nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')});render();
